{{- range $svc := .Values.services }}
{{- if $svc.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.serviceFullname" (dict "root" $ "service" $svc) }}
  namespace: {{ $.Values.namespace | default "default" }}
  labels:
    {{- include "app.serviceLabels" (dict "root" $ "service" $svc) | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ $svc.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "app.selectorLabels" (dict "root" $ "service" $svc) | nindent 4 }}
{{- end }}
{{- end }}
